### ISSUE TITLE
JWT tokens are always expired

### ISSUE THREAD

**Issue by ClemaX** [NATHAN76543217/ft_transcendance#12]
When I decode a JWT token using [this](https://jwt.io/) online tool, the expiration time (`exp`) is equal to the issued-at (`iat`) time. 

I temporarily disabled expiration, but we need to find the source of this problem.

**Comment by bjacob-56** [comment]
The source was in the authentication module, a 's' was missing in the 'expiresIn' attributes to indicate 'seconds'.
It's now fixed on main.
Maybe we still need to implement refresh token.
