### ISSUE TITLE
ERROR: for frontend  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by bjacob-56** [NATHAN76543217/ft_transcendance#25]
I sometimes have an error when building the containers : 
`ERROR: for frontend  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

It can be kind of fixed with the latter command on our session :
`export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120`

The problem is that a random tester won't know that he has to export those var. Should we do something on docker-compose ?

**Comment by ClemaX** [comment]
We can add these vars in our bash/zsh profiles (.zshrc). I think the slow school-computer disks are repsponsible.
If we build production images, the performance may improve.
