### ISSUE TITLE
User online status

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#33]
Browser: Mozilla Firefox 88.0.1
Not testest in more browsers yet

1) Open a Mozilla window and login 
2) Open another window and to the same
3) In 1st window client, the 2nd window's client is online
4) However, in the 2nd window client, the 1st window's client is offline

**Comment by pablo-lamtenzan** [comment]
![Screenshot_20210731_184818](https://user-images.githubusercontent.com/49682188/127746780-e9a8c377-ddd6-48d4-af62-1fb90c49ebef.png)

**Comment by pablo-lamtenzan** [comment]
The cause if this could be that i can't just have 2 clients opened at the same time in the same computer, perhabs have to launch a browser in a docker to test better

**Comment by bjacob-56** [comment]
It's not a real issue in my opinion.
I had the same problem with one browser, but it was fine if I used two different browsers.

**Comment by ClemaX** [comment]
I had this problem when using a regular and a private window, so i think this needs to be fixed.

**Comment by pablo-lamtenzan** [comment]
I think this is the root of complex issues (like #34) so I agree, it could be a good idea to fix it.

**Comment by bjacob-56** [comment]
The problem comes from the initialisation of the 'matches' sockets in /game pages, which also inititialize again an 'events' socket.
We need to only initialise a 'matches' socket.

**Comment by ClemaX** [comment]
Will be solved in #56
