### ISSUE TITLE
Client invitation (http / socket descyncronization)

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#34]
NOTE: Perhabs is related with issue #33 (where only one player can see that the other player online), in the case of inviting from the user that sees the other player online to the client that don't. 

When the the host invites the guest, the invite is sent to the host instead of the guest.

Steps to reproduce: #33 & click on "Invite to play" on right side of the home page.

**Comment by pablo-lamtenzan** [comment]
![Screenshot_20210731_184958](https://user-images.githubusercontent.com/49682188/127746810-b3d38e49-f214-4078-9c52-6a91dce0e8b0.png)

![Screenshot_20210731_185033](https://user-images.githubusercontent.com/49682188/127746820-e1fe78a9-eee3-4a8d-901e-816c2366825d.png)

**Comment by pablo-lamtenzan** [comment]
Ok, after checking better, the bug consists on:
1) Some part of the application run on sockets
2) Other part run on http requests

When 2 sessions are opened in 2 browser's windows, each time a login is performed the previous session is overwritten. There only can be an unique autheticated session running at the same time. But for apply the changes a page reload is needed.

So: 
1) User "aaaa" logins in a browser page
2) User "bbbb" logins in another browser page (overwrites "aaaa" but client need to reload the page to update data)
3) User "aaaa" sees "bbbb" online & can invite it (it seen itself ?)
4) The invite arrives to user "bbbb" (sent from "bbbb" to "bbbb" or "aaaa" to "bbbb" ?!?!)

Futhermore the game is launched on clicking on "Invite to game" button but this is another issue (see more at #35)

**Comment by pablo-lamtenzan** [comment]
LOL i can change pages on user "aaaa" when "aaaa" is disconnected (and "bbbb" is logged in). Reload is never performed.

**Comment by bjacob-56** [comment]
Website is not supposed to work on two 'normal' tabs.
Tests need to be done with at least one private tab.
