### ISSUE TITLE
Invited guest cannot reject an invitation

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#36]
A listener for matches rejections is implemented in matches.gateway.ts (listenning to the event ServerMessages.REJECT).
This issue can be solved just adding a button on the invited pop up and emit an event to server's listener.

NOTE: ServerMessages path's: `frontend/srcs/src/pages/games/pong/dto/messages`

**Comment by bjacob-56** [comment]
Not a problem or necessary in my opinion, the invitation will just remain pending.
A second button to cancel the invitation would mean more place needed in the friendsBar.

**Comment by pablo-lamtenzan** [comment]
Matches gateway need to know when a invitation is not accepted. It could be done using a "reject button", a timeout (expiration data of the invitation) or both.

If we don't implement "reject button" we must use a timeout. That means the invitation remains pending until the timeout cancel it. When the timeout is acomplished, the server must sent an event to the client to hide the "accept" button.

So, in client side we still something the handle this, or a  "cancel" button, a listener for the timeout for the expiration of the invitation or both. In my opinion we NEED the timeout to avoid bugs, an the button just will make the host not wait for all the timeout each time a guest don't wanna play.

Another interesting point is to let the host perform N invitations but only the guest that fit in the room (2 or 4 players) can join. How join first win

**Comment by pablo-lamtenzan** [comment]
(missclicked on my phone, this continues prev comment)

Another interesting point is to let the host perform N invitations but only the guest that fit in the room (2 or 4 players) can join. Who join first win it place in the room, other invitations are automatically expired/canceled. That way we won't need a "reject button" . NOTE: I think an invitation timeout is also needed to just avoid bugs.
