### ISSUE TITLE
What still need to be done on pong (execpt debug & solve prev isssues) ?

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#37]
- Parse ruleset's team size using a range slider
- Very probable that mouse position need to be normalized before to be sent to the server (just a rule of 3)
NOTE: import this to solve `import { canvasHeight, canvasWidth } from "../../../models/game/canvasDims";`
- Set up the termination time for a finished game on function onGameEnd in the matches gateway.
- Redirect to matchmaking page when HOME's "Let's play!" is clicked.

**Comment by ClemaX** [comment]
I have separated the issues to keep track of them individually.
