### ISSUE TITLE
On registration the 2 "login" buttons don't have the same behaviour

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#50]
Once a new is registered on the page, a new button "login" appears right-bellow the registration form. When this button is clicked user must write it username & password another time. However, there's another "login" button right-above the registration form and when this one is clicked on it logs using oauth.

**Comment by bjacob-56** [comment]
The fact that the user has to write its name and password again after registration is the expected behaviour.
The login button in the header redirects to the same login page.
