### ISSUE TITLE
Find/Invent a good method to handle circular invitations

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#53]
Let 3 players: p1, p2, p3.

- p1 is host of p2 (and p2 guest of p1)
- p2 is host of p3 (and p3 is guest of p2) 
- p3 is host of p1 (p1 is guest of p3)

If p1 accept it invitation and then p2 accept it invitation. If the invitation of p1 to p2 has not expired we may have bugs.

For 2vs2 game the complexity of this problem increases significantly, literally in any case it could be a circular invitation.

We need to find a simple way to handle this.

**Comment by ClemaX** [comment]
Solved by popup.
