### ISSUE TITLE
Players are not redirected to the same room on create game

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#54]

**Comment by pablo-lamtenzan** [comment]
Props on `pong.tsx` contains a different id. That's why.

**Comment by ClemaX** [comment]
I had this bug to, seems to be a substring (player 0 joined 23, player 1 joined 3)

**Comment by bjacob-56** [comment]
We used to redirect the second player by using the message id and not the room id.
This has been fixed in the last commit.
