### ISSUE TITLE
Problem with matches path

### ISSUE THREAD

**Issue by pablo-lamtenzan** [NATHAN76543217/ft_transcendance#58]
Steps to reproduce:
1) Type the following URL: `https://localhost/game/`
2) Then click on "Fast Game" (or "Create Game")
3) Now URL is: `https://localhost/game/game/matchmaking`
NOTE: Correct one should be: `https://localhost/game/matchmaking`

NOTE: We must test this bug in the whole app

How this bug can be found by an user without manually modifying the URL ?
1) User goes to home page, then game, then matchmaking, then found a match (path should be: `https://localhost/game/$ID`)
2) User click go back in its browser 2 times (now path should be: `https://localhost/game/`
3) Then click on "Fast Game"

**Comment by ClemaX** [comment]
maybe a `/` or `./`.

**Comment by pablo-lamtenzan** [comment]
Understood

**Comment by bjacob-56** [comment]
This is handled in the last commit.
We had to redirect to '/game/matchmaking' instead of 'game/matchmaking'.
