### ISSUE TITLE
Add speed and downsizing mode to pong

### ISSUE THREAD

**Issue by bjacob-56** [NATHAN76543217/ft_transcendance#65]

**Comment by pablo-lamtenzan** [comment]
speed for each paddle rebound is handled as: `st.ball.velocity += 0.1 + (0.1 * Number(speedMode));`

downsize for each score is handled as: ball.rad = defaultBall.rad - ((defaultBall.rad / 20) * Number(downsize))`

NOTE: Server only apply those changes, need to test if client predicter engine need them too. But before i need to solve other problems (like: why the ball rad is small af ?). For that reason, i strongly recomend to not close this issue.

**Comment by pablo-lamtenzan** [comment]
done
